import { TelecomScreenConfig } from './model/telecom.model';

export const TELECOM_SCREENS: Record<string, TelecomScreenConfig> = {
  documentations: {
    key: 'documentations',
    title: 'Documentation',
    baseUrl: '/api/documentations',
    route: 'documentations',
    fields: [
      { key: 'documentationType', label: 'Documentation Type' },
      { key: 'directClient', label: 'Direct Client' },
      { key: 'directClientManager', label: 'Direct Client Manager' },
      { key: 'finalClient', label: 'Final Client' },
      { key: 'finalClientManager', label: 'Final Client Manager' },
      { key: 'projectType', label: 'Project Type' },
      { key: 'projectNumber', label: 'Project Number' },
      { key: 'purchaseOrder', label: 'Purchase Order' },
      { key: 'serviceOrder', label: 'Service Order' },
      { key: 'technician', label: 'Technician' },
      { key: 'address', label: 'Address' },
      { key: 'addressNumber', label: 'Number' },
      { key: 'addressComplement', label: 'Complement' },
      { key: 'district', label: 'District' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'zipCode', label: 'Zip Code' },
      { key: 'latitudeLongitude', label: 'Latitude and Longitude' },
      { key: 'siteId', label: 'Site ID' },
      { key: 'addressId', label: 'Address ID' },
      { key: 'projectPhase', label: 'Project Phase' },
      { key: 'activityType', label: 'Activity Type' },
      { key: 'scheduledDate', label: 'Scheduled Date' },
      { key: 'scheduledTime', label: 'Scheduled Time' },
      { key: 'finalClientName', label: 'Final Client Name' },
      { key: 'finalClientContact', label: 'Final Client Contact' },
      { key: 'finalClientEmail', label: 'Final Client Email' },
      { key: 'materialUsed', label: 'Material Used' },
      { key: 'note1', label: 'Note 1' },
      { key: 'note2', label: 'Note 2' }
    ]
  },
  billings: {
    key: 'billings',
    title: 'Billing',
    baseUrl: '/api/billings',
    route: 'billings',
    fields: [
      { key: 'legalName', label: 'Legal Name' },
      { key: 'taxId', label: 'Tax ID' },
      { key: 'billingAddress', label: 'Billing Address' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
      { key: 'issueDate', label: 'Issue Date' },
      { key: 'dueDate', label: 'Due Date' },
      { key: 'startDate', label: 'Start Date' },
      { key: 'endDate', label: 'End Date' },
      { key: 'competenceMonth', label: 'Competence Month' },
      { key: 'totalAmount', label: 'Total Amount' },
      { key: 'finalClientManager', label: 'Final Client Manager' },
      { key: 'projectType', label: 'Project Type' },
      { key: 'projectNumber', label: 'Project Number' },
      { key: 'purchaseOrder', label: 'Purchase Order' },
      { key: 'serviceOrder', label: 'Service Order' },
      { key: 'poNumber', label: 'PO' },
      { key: 'finalClient', label: 'Final Client' },
      { key: 'description', label: 'Description' },
      { key: 'freelancerAmount', label: 'Freelancer Amount' },
      { key: 'materialsAmount', label: 'Materials Amount' },
      { key: 'freightAmount', label: 'Freight Amount' },
      { key: 'dailyRate', label: 'Daily Rate' },
      { key: 'technicianCount', label: 'Technician Count' },
      { key: 'actualActivityDuration', label: 'Actual Activity Duration' },
      { key: 'taxIss', label: 'Tax (ISS)' },
      { key: 'taxIcms', label: 'Tax (ICMS)' },
      { key: 'taxPis', label: 'Tax (PIS)' },
      { key: 'taxCofins', label: 'Tax (COFINS)' }
    ]
  },
  vehicleRegistrationInfos: {
    key: 'vehicleRegistrationInfos',
    title: 'Vehicle Registration Information',
    baseUrl: '/api/vehicle-registration-infos',
    route: 'vehicle-registration-infos',
    fields: [
      { key: 'licensePlate', label: 'License Plate' },
      { key: 'renavam', label: 'Renavam' },
      { key: 'chassis', label: 'Chassis' },
      { key: 'vehicleType', label: 'Vehicle Type' },
      { key: 'category', label: 'Category' },
      { key: 'makeModel', label: 'Make / Model' },
      { key: 'manufactureYear', label: 'Manufacture Year' },
      { key: 'modelYear', label: 'Model Year' },
      { key: 'color', label: 'Color' },
      { key: 'capacity', label: 'Capacity (cargo/passengers)' },
      { key: 'currentMileage', label: 'Current Mileage' },
      { key: 'crlv', label: 'CRLV' },
      { key: 'ipvaStatus', label: 'IPVA Status' },
      { key: 'registrationExpiry', label: 'Registration Expiry' },
      { key: 'finesStatus', label: 'Fines Status' },
      { key: 'insuranceStatus', label: 'Insurance Status' },
      { key: 'insuranceExpiryDate', label: 'Insurance Expiry Date' },
      { key: 'companyOrThirdParty', label: 'Company or Third Party' },
      { key: 'ownerName', label: 'Owner Name' },
      { key: 'taxId', label: 'Tax ID' },
      { key: 'serviceHistory', label: 'Service History' },
      { key: 'nextScheduledService', label: 'Next Scheduled Service' },
      { key: 'oilChange', label: 'Oil Change' },
      { key: 'tireMaintenance', label: 'Tire Maintenance' },
      { key: 'damageRepairRecords', label: 'Damage and Repair Records' },
      { key: 'fuelType', label: 'Fuel Type' },
      { key: 'averageConsumption', label: 'Average Consumption' },
      { key: 'fuelingHistory', label: 'Fueling History' },
      { key: 'note1', label: 'Note 1' },
      { key: 'note2', label: 'Note 2' }
    ]
  },
  userRegistrations: {
    key: 'userRegistrations',
    title: 'User Registration',
    baseUrl: '/api/user-registrations',
    route: 'user-registrations',
    fields: [
      { key: 'fullName', label: 'Full Name' },
      { key: 'rg', label: 'RG' },
      { key: 'issuingAuthority', label: 'Issuing Authority' },
      { key: 'issueDate', label: 'Issue Date' },
      { key: 'birthDate', label: 'Birth Date' },
      { key: 'motherName', label: "Mother's Name" },
      { key: 'fatherName', label: "Father's Name" },
      { key: 'cpf', label: 'CPF' },
      { key: 'birthplace', label: 'Birthplace' },
      { key: 'birthState', label: 'Birth State' },
      { key: 'address', label: 'Address' },
      { key: 'addressNumber', label: 'Number' },
      { key: 'addressComplement', label: 'Complement' },
      { key: 'district', label: 'District' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'zipCode', label: 'Zip Code' },
      { key: 'username', label: 'Username' },
      { key: 'password', label: 'Password' },
      { key: 'permissionLevel', label: 'Permission Level' },
      { key: 'jobTitle', label: 'Job Title' },
      { key: 'cltOrCnpj', label: 'CLT or CNPJ' },
      { key: 'hireDate', label: 'Hire Date' },
      { key: 'asoExpiry', label: 'ASO Expiry' },
      { key: 'nr10Expiry', label: 'NR10 Expiry' },
      { key: 'nr35Expiry', label: 'NR35 Expiry' },
      { key: 'status', label: 'Status' },
      { key: 'note1', label: 'Note 1' },
      { key: 'note2', label: 'Note 2' },
      { key: 'note3', label: 'Note 3' }
    ]
  },
  claroSites: {
    key: 'claroSites',
    title: 'Claro Site',
    baseUrl: '/api/claro-sites',
    route: 'claro-sites',
    fields: [
      { key: 'siteId', label: 'ID' },
      { key: 'name', label: 'Name' },
      { key: 'anatelTx', label: 'Anatel TX' },
      { key: 'anatelRf', label: 'Anatel RF' },
      { key: 'anatelNetwork', label: 'Anatel Network' },
      { key: 'elevation', label: 'Elevation' },
      { key: 'latitude', label: 'Latitude' },
      { key: 'longitude', label: 'Longitude' },
      { key: 'latitudeDms', label: 'Latitude DMS' },
      { key: 'longitudeDms', label: 'Longitude DMS' },
      { key: 'geoCluster', label: 'Geo Cluster' },
      { key: 'datum', label: 'Datum' },
      { key: 'ibge', label: 'IBGE' },
      { key: 'infraSla', label: 'Infra SLA' },
      { key: 'omrClassification', label: 'OMR Classification' },
      { key: 'contractClass', label: 'Contract Class' },
      { key: 'gsmUmtsLteLicenses', label: 'GSM / UMTS / LTE Licenses' },
      { key: 'note1', label: 'Note 1' },
      { key: 'note2', label: 'Note 2' },
      { key: 'note3', label: 'Note 3' }
    ]
  },
  timSites: {
    key: 'timSites',
    title: 'TIM Site',
    baseUrl: '/api/tim-sites',
    route: 'tim-sites',
    fields: [
      { key: 'siteId', label: 'Site ID' },
      { key: 'elementType', label: 'Element Type' },
      { key: 'technology', label: 'Technology' },
      { key: 'connectionType', label: 'Connection Type' },
      { key: 'classification', label: 'Classification' },
      { key: 'acquisitionDate', label: 'Acquisition Date' },
      { key: 'constructionDate', label: 'Construction Date' },
      { key: 'activationDate', label: 'Activation Date' },
      { key: 'deactivationDate', label: 'Deactivation Date' },
      { key: 'justification', label: 'Justification' },
      { key: 'towerType', label: 'Tower Type' },
      { key: 'nominalAev', label: 'Nominal AEV' },
      { key: 'structureHeight', label: 'Structure Height' },
      { key: 'spazioUpdateStatus', label: 'Spazio Update Status' }
    ]
  },
  vivoSites: {
    key: 'vivoSites',
    title: 'Vivo Site',
    baseUrl: '/api/vivo-sites',
    route: 'vivo-sites',
    fields: [
      { key: 'sequence', label: 'Sequence' },
      { key: 'stateAbbreviation', label: 'State Abbreviation' },
      { key: 'state', label: 'State' },
      { key: 'name', label: 'Name' },
      { key: 'abbreviation', label: 'Abbreviation' },
      { key: 'gvOiFixedAbbreviation', label: 'GV / OI / Fixed Abbreviation' },
      { key: 'ssiAddress', label: 'SSI Address' },
      { key: 'altitude', label: 'Altitude' },
      { key: 'maintenancePending', label: 'Maintenance Pending' },
      { key: 'thirdPartyArea', label: 'Third-Party Area' },
      { key: 'structure', label: 'Structure' },
      { key: 'vipSite', label: 'VIP Site' },
      { key: 'note1', label: 'Note 1' },
      { key: 'note2', label: 'Note 2' },
      { key: 'note3', label: 'Note 3' }
    ]
  },
  contractRegistrations: {
    key: 'contractRegistrations',
    title: 'Contract Registration',
    baseUrl: '/api/contract-registrations',
    route: 'contract-registrations',
    fields: [
      { key: 'directClient', label: 'Direct Client' },
      { key: 'directClientManager', label: 'Direct Client Manager' },
      { key: 'finalClient', label: 'Final Client' },
      { key: 'finalClientManager', label: 'Final Client Manager' },
      { key: 'projectType', label: 'Project Type' },
      { key: 'projectNumber', label: 'Project Number' },
      { key: 'purchaseOrder', label: 'Purchase Order' },
      { key: 'serviceOrder', label: 'Service Order' },
      { key: 'poNumber', label: 'PO' },
      { key: 'siteId', label: 'Site ID' },
      { key: 'addressId', label: 'Address ID' },
      { key: 'totalProjectValue', label: 'Total Project Value' },
      { key: 'projectPhases', label: 'Project Phases' }
    ]
  },
  tickets: {
    key: 'tickets',
    title: 'Tickets',
    baseUrl: '/api/tickets',
    route: 'tickets',
    fields: [
      { key: 'ticketNumber', label: 'Ticket Number' },
      { key: 'directClient', label: 'Direct Client' },
      { key: 'directClientManager', label: 'Direct Client Manager' },
      { key: 'finalClient', label: 'Final Client' },
      { key: 'finalClientManager', label: 'Final Client Manager' },
      { key: 'projectType', label: 'Project Type' },
      { key: 'projectNumber', label: 'Project Number' },
      { key: 'purchaseOrder', label: 'Purchase Order' },
      { key: 'serviceOrder', label: 'Service Order' },
      { key: 'poNumber', label: 'PO' },
      { key: 'address', label: 'Address' },
      { key: 'addressNumber', label: 'Number' },
      { key: 'addressComplement', label: 'Complement' },
      { key: 'district', label: 'District' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'zipCode', label: 'Zip Code' },
      { key: 'latitudeLongitude', label: 'Latitude and Longitude' },
      { key: 'siteType', label: 'Site Type' },
      { key: 'accessReleaseNumber', label: 'Access Release Number' },
      { key: 'tbsaId', label: 'TBSA ID' },
      { key: 'tbsaTicket', label: 'TBSA Ticket' },
      { key: 'activityDescription', label: 'Activity Description' }
    ]
  }
};

export const getTelecomScreen = (key: string): TelecomScreenConfig | undefined =>
  TELECOM_SCREENS[key];
