import { TelecomScreenConfig } from './model/telecom.model';

export const TELECOM_SCREENS: Record<string, TelecomScreenConfig> = {
  documentations: {
    key: 'documentations',
    title: 'Documentation',
    baseUrl: '/api/documentations',
    route: 'documentations',
    fields: [
      { key: 'documentationType', label: 'Documentation Type' },
      { key: 'directClient', label: 'Direct Client' },
      { key: 'directClientManager', label: 'Direct Client Manager' },
      { key: 'finalClient', label: 'Final Client' },
      { key: 'finalClientManager', label: 'Final Client Manager' },
      { key: 'projectType', label: 'Project Type' },
      { key: 'projectNumber', label: 'Project Number' },
      { key: 'purchaseOrder', label: 'Purchase Order' },
      { key: 'serviceOrder', label: 'Service Order' },
      { key: 'technician', label: 'Technician' },
      { key: 'address', label: 'Address' },
      { key: 'addressNumber', label: 'Number' },
      { key: 'addressComplement', label: 'Complement' },
      { key: 'district', label: 'District' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'zipCode', label: 'Zip Code' },
      { key: 'latitudeLongitude', label: 'Latitude and Longitude' },
      { key: 'siteId', label: 'Site ID' },
      { key: 'addressId', label: 'Address ID' },
      { key: 'projectPhase', label: 'Project Phase' },
      { key: 'activityType', label: 'Activity Type' },
      { key: 'scheduledDate', label: 'Scheduled Date' },
      { key: 'scheduledTime', label: 'Scheduled Time' },
      { key: 'finalClientName', label: 'Final Client Name' },
      { key: 'finalClientContact', label: 'Final Client Contact' },
      { key: 'finalClientEmail', label: 'Final Client Email' },
      { key: 'materialUsed', label: 'Material Used' },
      { key: 'note1', label: 'Note 1' },
      { key: 'note2', label: 'Note 2' }
    ]
  },
  billings: {
    key: 'billings',
    title: 'Billing',
    baseUrl: '/api/billings',
    route: 'billings',
    fields: [
      { key: 'legalName', label: 'Legal Name', required: true, showInList: true },
      { key: 'taxId', label: 'Tax ID', required: true, showInList: true },
      { key: 'billingAddress', label: 'Billing Address', required: true },
      { key: 'phone', label: 'Phone', required: true },
      { key: 'email', label: 'Email', required: true },
      { key: 'issueDate', label: 'Issue Date', required: true, showInList: true },
      { key: 'dueDate', label: 'Due Date', required: true },
      { key: 'startDate', label: 'Start Date', required: true },
      { key: 'endDate', label: 'End Date', required: true },
      { key: 'competenceMonth', label: 'Competence Month', required: true },
      { key: 'totalAmount', label: 'Total Amount', required: true, showInList: true },
      { key: 'finalClientManager', label: 'Final Client Manager', autoFill: true, readOnly: true },
      { key: 'projectType', label: 'Project Type', autoFill: true, readOnly: true },
      { key: 'projectNumber', label: 'Project Number', autoFill: true, readOnly: true },
      { key: 'purchaseOrder', label: 'Purchase Order', autoFill: true, readOnly: true },
      { key: 'serviceOrder', label: 'Service Order', autoFill: true, readOnly: true },
      { key: 'poNumber', label: 'PO', autoFill: true, readOnly: true },
      { key: 'finalClient', label: 'Final Client', autoFill: true, readOnly: true },
      { key: 'description', label: 'Description', required: true },
      { key: 'freelancerAmount', label: 'Freelancer Amount', required: true },
      { key: 'materialsAmount', label: 'Materials Amount', required: true },
      { key: 'freightAmount', label: 'Freight Amount', required: true },
      { key: 'dailyRate', label: 'Daily Rate', required: true },
      { key: 'technicianCount', label: 'Technician Count', required: true },
      { key: 'actualActivityDuration', label: 'Actual Activity Duration', required: true },
      { key: 'taxIss', label: 'Tax (ISS)', required: true },
      { key: 'taxIcms', label: 'Tax (ICMS)', required: true },
      { key: 'taxPis', label: 'Tax (PIS)', required: true },
      { key: 'taxCofins', label: 'Tax (COFINS)', required: true }
    ]
  },
  vehicleRegistrationInfos: {
    key: 'vehicleRegistrationInfos',
    title: 'Vehicle Registration Information',
    baseUrl: '/api/vehicle-registration-infos',
    route: 'vehicle-registration-infos',
    fields: [
      { key: 'licensePlate', label: 'License Plate' },
      { key: 'renavam', label: 'Renavam' },
      { key: 'chassis', label: 'Chassis' },
      { key: 'vehicleType', label: 'Vehicle Type' },
      { key: 'category', label: 'Category' },
      { key: 'makeModel', label: 'Make / Model' },
      { key: 'manufactureYear', label: 'Manufacture Year' },
      { key: 'modelYear', label: 'Model Year' },
      { key: 'color', label: 'Color' },
      { key: 'capacity', label: 'Capacity (cargo/passengers)' },
      { key: 'currentMileage', label: 'Current Mileage' },
      { key: 'crlv', label: 'CRLV' },
      { key: 'ipvaStatus', label: 'IPVA Status' },
      { key: 'registrationExpiry', label: 'Registration Expiry' },
      { key: 'finesStatus', label: 'Fines Status' },
      { key: 'insuranceStatus', label: 'Insurance Status' },
      { key: 'insuranceExpiryDate', label: 'Insurance Expiry Date' },
      { key: 'companyOrThirdParty', label: 'Company or Third Party' },
      { key: 'ownerName', label: 'Owner Name' },
      { key: 'taxId', label: 'Tax ID' },
      { key: 'serviceHistory', label: 'Service History' },
      { key: 'nextScheduledService', label: 'Next Scheduled Service' },
      { key: 'oilChange', label: 'Oil Change' },
      { key: 'tireMaintenance', label: 'Tire Maintenance' },
      { key: 'damageRepairRecords', label: 'Damage and Repair Records' },
      { key: 'fuelType', label: 'Fuel Type' },
      { key: 'averageConsumption', label: 'Average Consumption' },
      { key: 'fuelingHistory', label: 'Fueling History' },
      { key: 'note1', label: 'Note 1' },
      { key: 'note2', label: 'Note 2' }
    ]
  },
  userRegistrations: {
    key: 'userRegistrations',
    title: 'User Registration',
    baseUrl: '/api/user-registrations',
    route: 'user-registrations',
    fields: [
      { key: 'fullName', label: 'Full Name' },
      { key: 'rg', label: 'RG' },
      { key: 'issuingAuthority', label: 'Issuing Authority' },
      { key: 'issueDate', label: 'Issue Date' },
      { key: 'birthDate', label: 'Birth Date' },
      { key: 'motherName', label: "Mother's Name" },
      { key: 'fatherName', label: "Father's Name" },
      { key: 'cpf', label: 'CPF' },
      { key: 'birthplace', label: 'Birthplace' },
      { key: 'birthState', label: 'Birth State' },
      { key: 'address', label: 'Address' },
      { key: 'addressNumber', label: 'Number' },
      { key: 'addressComplement', label: 'Complement' },
      { key: 'district', label: 'District' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'zipCode', label: 'Zip Code' },
      { key: 'username', label: 'Username' },
      { key: 'password', label: 'Password' },
      { key: 'permissionLevel', label: 'Permission Level' },
      { key: 'jobTitle', label: 'Job Title' },
      { key: 'cltOrCnpj', label: 'CLT or CNPJ' },
      { key: 'hireDate', label: 'Hire Date' },
      { key: 'asoExpiry', label: 'ASO Expiry' },
      { key: 'nr10Expiry', label: 'NR10 Expiry' },
      { key: 'nr35Expiry', label: 'NR35 Expiry' },
      { key: 'status', label: 'Status' },
      { key: 'note1', label: 'Note 1' },
      { key: 'note2', label: 'Note 2' },
      { key: 'note3', label: 'Note 3' }
    ]
  },
  claroSites: {
    key: 'claroSites',
    title: 'Claro Site',
    baseUrl: '/api/claro-sites',
    route: 'claro-sites',
    fields: [
      { key: 'siteId', label: 'ID', required: true, showInList: true },
      { key: 'addressId', label: 'Address ID', required: true, showInList: true },
      { key: 'name', label: 'Name', required: true, showInList: true },
      { key: 'latitude', label: 'Latitude', required: true, showInList: true },
      { key: 'longitude', label: 'Longitude', required: true, showInList: true },
      { key: 'anatelTx', label: 'Anatel TX', optional: true },
      { key: 'anatelRf', label: 'Anatel RF', optional: true },
      { key: 'anatelNetwork', label: 'Anatel Network', optional: true },
      { key: 'elevation', label: 'Elevation', optional: true },
      { key: 'latitudeDms', label: 'Latitude DMS', optional: true },
      { key: 'longitudeDms', label: 'Longitude DMS', optional: true },
      { key: 'geoCluster', label: 'Geo Cluster', optional: true },
      { key: 'datum', label: 'Datum', optional: true },
      { key: 'ibge', label: 'IBGE', optional: true },
      { key: 'infraSla', label: 'Infra SLA', optional: true },
      { key: 'omrClassification', label: 'OMR Classification', optional: true },
      { key: 'contractClass', label: 'Contract Class', optional: true },
      { key: 'gsmUmtsLteLicenses', label: 'GSM / UMTS / LTE Licenses', optional: true },
      { key: 'note1', label: 'Note 1', optional: true },
      { key: 'note2', label: 'Note 2', optional: true },
      { key: 'note3', label: 'Note 3', optional: true }
    ]
  },
  timSites: {
    key: 'timSites',
    title: 'TIM Site',
    baseUrl: '/api/tim-sites',
    route: 'tim-sites',
    fields: [
      { key: 'siteId', label: 'Site ID', required: true, showInList: true },
      { key: 'addressId', label: 'Address ID', required: true, showInList: true },
      { key: 'classification', label: 'Classification', required: true, showInList: true },
      { key: 'elementType', label: 'Element Type', optional: true },
      { key: 'technology', label: 'Technology', optional: true },
      { key: 'connectionType', label: 'Connection Type', optional: true },
      { key: 'acquisitionDate', label: 'Acquisition Date', optional: true },
      { key: 'constructionDate', label: 'Construction Date', optional: true },
      { key: 'activationDate', label: 'Activation Date', optional: true },
      { key: 'deactivationDate', label: 'Deactivation Date', optional: true },
      { key: 'justification', label: 'Justification', optional: true },
      { key: 'towerType', label: 'Tower Type', optional: true },
      { key: 'nominalAev', label: 'Nominal AEV', optional: true },
      { key: 'structureHeight', label: 'Structure Height', optional: true },
      { key: 'spazioUpdateStatus', label: 'Spazio Update Status', optional: true }
    ]
  },
  vivoSites: {
    key: 'vivoSites',
    title: 'Vivo Site',
    baseUrl: '/api/vivo-sites',
    route: 'vivo-sites',
    fields: [
      { key: 'sequence', label: 'Sequence', required: true, showInList: true },
      { key: 'addressId', label: 'Address ID', required: true, showInList: true },
      { key: 'stateAbbreviation', label: 'State Abbreviation', required: true, showInList: true },
      { key: 'state', label: 'State', required: true, showInList: true },
      { key: 'name', label: 'Name', required: true, showInList: true },
      { key: 'abbreviation', label: 'Abbreviation', required: true },
      { key: 'gvOiFixedAbbreviation', label: 'GV / OI / Fixed Abbreviation', optional: true },
      { key: 'ssiAddress', label: 'SSI Address', optional: true },
      { key: 'altitude', label: 'Altitude', optional: true },
      { key: 'maintenancePending', label: 'Maintenance Pending', optional: true },
      { key: 'thirdPartyArea', label: 'Third-Party Area', optional: true },
      { key: 'structure', label: 'Structure', optional: true },
      { key: 'vipSite', label: 'VIP Site', optional: true },
      { key: 'note1', label: 'Note 1', optional: true },
      { key: 'note2', label: 'Note 2', optional: true },
      { key: 'note3', label: 'Note 3', optional: true }
    ]
  },
  contractRegistrations: {
    key: 'contractRegistrations',
    title: 'Contract Registration',
    baseUrl: '/api/contract-registrations',
    route: 'contract-registrations',
    fields: [
      {
        key: 'siteType',
        label: 'Site Type',
        inputType: 'select',
        options: [
          { value: 'claro', label: 'Claro' },
          { value: 'tim', label: 'TIM' },
          { value: 'vivo', label: 'Vivo' }
        ],
        required: true,
        optional: true,
        showInList: true
      },
      { key: 'siteId', label: 'Site ID', required: true, optional: true, showInList: true },
      { key: 'addressId', label: 'Address ID', required: true, optional: true, showInList: true },
      { key: 'directClient', label: 'Direct Client', required: true, showInList: true },
      { key: 'directClientManager', label: 'Direct Client Manager', required: true },
      { key: 'finalClient', label: 'Final Client', required: true },
      { key: 'finalClientManager', label: 'Final Client Manager', required: true },
      { key: 'projectType', label: 'Project Type', required: true },
      { key: 'projectNumber', label: 'Project Number', required: true },
      { key: 'purchaseOrder', label: 'Purchase Order', required: true },
      { key: 'serviceOrder', label: 'Service Order', required: true },
      { key: 'poNumber', label: 'PO', required: true },
      { key: 'totalProjectValue', label: 'Total Project Value', required: true },
      { key: 'projectPhases', label: 'Project Phases', optional: true }
    ]
  },
  tickets: {
    key: 'tickets',
    title: 'Tickets',
    baseUrl: '/api/tickets',
    route: 'tickets',
    fields: [
      { key: 'ticketNumber', label: 'Ticket Number', optional: true },
      { key: 'directClient', label: 'Direct Client', autoFill: true, readOnly: true, showInList: true },
      { key: 'directClientManager', label: 'Direct Client Manager', autoFill: true, readOnly: true },
      { key: 'finalClient', label: 'Final Client', autoFill: true, readOnly: true, showInList: true },
      { key: 'finalClientManager', label: 'Final Client Manager', autoFill: true, readOnly: true },
      { key: 'projectType', label: 'Project Type', autoFill: true, readOnly: true },
      { key: 'projectNumber', label: 'Project Number', autoFill: true, readOnly: true, showInList: true },
      { key: 'purchaseOrder', label: 'Purchase Order', autoFill: true, readOnly: true },
      { key: 'serviceOrder', label: 'Service Order', autoFill: true, readOnly: true },
      { key: 'poNumber', label: 'PO', autoFill: true, readOnly: true },
      { key: 'address', label: 'Address', optional: true },
      { key: 'addressNumber', label: 'Number', optional: true },
      { key: 'addressComplement', label: 'Complement', optional: true },
      { key: 'district', label: 'District', optional: true },
      { key: 'city', label: 'City', optional: true },
      { key: 'state', label: 'State', optional: true },
      { key: 'zipCode', label: 'Zip Code', optional: true },
      { key: 'latitudeLongitude', label: 'Latitude and Longitude', optional: true },
      { key: 'siteType', label: 'Site Type', autoFill: true, readOnly: true },
      { key: 'accessReleaseNumber', label: 'Access Release Number', required: true, showInList: true },
      { key: 'tbsaId', label: 'TBSA ID', required: true, showInList: true },
      { key: 'tbsaTicket', label: 'TBSA Ticket', required: true, showInList: true },
      { key: 'activityDescription', label: 'Activity Description', required: true }
    ]
  }
};

export const getTelecomScreen = (key: string): TelecomScreenConfig | undefined =>
  TELECOM_SCREENS[key];
