import { TelecomScreenConfig } from './model/telecom.model';

export const TELECOM_SCREENS: Record<string, TelecomScreenConfig> = {
  documentacoes: {
    key: 'documentacoes',
    title: 'Documentação',
    baseUrl: '/api/documentacoes',
    route: 'documentacoes',
    fields: [
      { key: 'tipoDocumentacao', label: 'Tipo Documentação' },
      { key: 'clienteDireto', label: 'Cliente Direto' },
      { key: 'gestorClienteDireto', label: 'Gestor Cliente Direto' },
      { key: 'clienteFinal', label: 'Cliente Final' },
      { key: 'gestorClienteFinal', label: 'Gestor Cliente Final' },
      { key: 'projetoTipo', label: 'Projeto Tipo' },
      { key: 'projetoNumero', label: 'Projeto Número' },
      { key: 'oc', label: 'OC' },
      { key: 'os', label: 'OS' },
      { key: 'tecnico', label: 'Técnico' },
      { key: 'endereco', label: 'Endereço' },
      { key: 'numero', label: 'Número' },
      { key: 'complemento', label: 'Complemento' },
      { key: 'bairro', label: 'Bairro' },
      { key: 'cidade', label: 'Cidade' },
      { key: 'uf', label: 'UF' },
      { key: 'cep', label: 'Cep' },
      { key: 'latitudeLongitude', label: 'Latitude e Longitude' },
      { key: 'siteId', label: 'Site ID' },
      { key: 'enderecoId', label: 'Endereço ID' },
      { key: 'faseProjeto', label: 'Fase do Projeto' },
      { key: 'tipoAtividade', label: 'Tipo de Atividade' },
      { key: 'dataAgendamento', label: 'Data Agendamento' },
      { key: 'horarioAgendamento', label: 'Horário Agendamento' },
      { key: 'nomeClienteFinal', label: 'Nome do Cliente Final' },
      { key: 'contatoClienteFinal', label: 'Contato Cliente Final' },
      { key: 'emailClienteFinal', label: 'E-mail Cliente Final' },
      { key: 'materialUtilizado', label: 'Material utilizado' },
      { key: 'observacao1', label: 'Observação 1' },
      { key: 'observacao2', label: 'Observação 2' }
    ]
  },
  faturamentos: {
    key: 'faturamentos',
    title: 'Faturamento',
    baseUrl: '/api/faturamentos',
    route: 'faturamentos',
    fields: [
      { key: 'nomeRazaoSocial', label: 'Nome/Razão Social' },
      { key: 'cnpjCpf', label: 'CNPJ/CPF' },
      { key: 'enderecoCobranca', label: 'Endereço Cobrança' },
      { key: 'telefone', label: 'Telefone' },
      { key: 'email', label: 'E-mail' },
      { key: 'dataEmissao', label: 'Data de Emissão' },
      { key: 'dataVencimento', label: 'Data de Vencimento' },
      { key: 'dataInicio', label: 'Data Início' },
      { key: 'dataTermino', label: 'Data Término' },
      { key: 'mesCompetencia', label: 'Mês de Competência' },
      { key: 'valorTotal', label: 'Valor Total' },
      { key: 'gestorClienteFinal', label: 'Gestor Cliente Final' },
      { key: 'projetoTipo', label: 'Projeto Tipo' },
      { key: 'projetoNumero', label: 'Projeto Número' },
      { key: 'oc', label: 'OC' },
      { key: 'os', label: 'OS' },
      { key: 'po', label: 'PO' },
      { key: 'clienteFinal', label: 'Cliente Final' },
      { key: 'descricao', label: 'Descrição' },
      { key: 'valorFreelancer', label: 'Valor Freelancer' },
      { key: 'valorMateriais', label: 'Valor Materiais' },
      { key: 'valorFrete', label: 'Valor Frete' },
      { key: 'valorDiaria', label: 'Valor Diária' },
      { key: 'quantidadeTecnicos', label: 'Quantidade de Técnicos' },
      { key: 'duracaoRealAtividade', label: 'Duração Real da Atividade' },
      { key: 'impostoIss', label: 'Imposto (ISS)' },
      { key: 'impostoIcms', label: 'Imposto (ICMS)' },
      { key: 'impostoPis', label: 'Imposto (PIS)' },
      { key: 'impostoCofins', label: 'Imposto (COFINS)' }
    ]
  },
  informacoesCadastroVeiculos: {
    key: 'informacoesCadastroVeiculos',
    title: 'Informações de Cadastro do Veículo',
    baseUrl: '/api/informacoes-cadastro-veiculos',
    route: 'informacoes-cadastro-veiculos',
    fields: [
      { key: 'placa', label: 'Placa' },
      { key: 'renavam', label: 'Renavam' },
      { key: 'chassi', label: 'Chassi' },
      { key: 'tipoVeiculo', label: 'Tipo de veículo' },
      { key: 'categoria', label: 'Categoria' },
      { key: 'marcaModelo', label: 'Marca / Modelo' },
      { key: 'anoFabricacao', label: 'Ano de fabricação' },
      { key: 'anoModelo', label: 'Ano do modelo' },
      { key: 'cor', label: 'Cor' },
      { key: 'capacidadeCargaPassageiros', label: 'Capacidade (carga/passageiros)' },
      { key: 'quilometragemAtual', label: 'Quilometragem atual' },
      { key: 'crlv', label: 'CRLV' },
      { key: 'situacaoIpva', label: 'Situação do IPVA' },
      { key: 'vencimentoLicenciamento', label: 'Vencimento do licenciamento' },
      { key: 'situacaoMultas', label: 'Situação de multas' },
      { key: 'seguroObrigatorioDpvatESeguroPrivado', label: 'Seguro obrigatório (DPVAT) e seguro privado' },
      { key: 'dataVencimentoSeguro', label: 'Data de vencimento do seguro' },
      { key: 'empresaOuTerceiro', label: 'Empresa ou terceiro' },
      { key: 'nomeProprietario', label: 'Nome do proprietário' },
      { key: 'cnpjCpf', label: 'CNPJ/CPF' },
      { key: 'historicoRevisoes', label: 'Histórico de revisões' },
      { key: 'proximaRevisaoProgramada', label: 'Próxima revisão programada' },
      { key: 'trocaOleo', label: 'Troca de óleo' },
      { key: 'manutencaoPneus', label: 'Manutenção de pneus' },
      { key: 'registroAvariasConsertos', label: 'Registro de avarias e consertos' },
      { key: 'tipoCombustivel', label: 'Tipo de combustível' },
      { key: 'consumoMedio', label: 'Consumo médio' },
      { key: 'historicoAbastecimento', label: 'Histórico de abastecimento' },
      { key: 'observacao1', label: 'Observação 1' },
      { key: 'observacao2', label: 'Observação 2' }
    ]
  },
  cadastroUsuarios: {
    key: 'cadastroUsuarios',
    title: 'Cadastro de Usuários',
    baseUrl: '/api/cadastro-usuarios',
    route: 'cadastro-usuarios',
    fields: [
      { key: 'nomeCompleto', label: 'Nome Completo' },
      { key: 'rg', label: 'RG' },
      { key: 'orgaoExpedidor', label: 'Órgão Expedidor' },
      { key: 'dataExpedicao', label: 'Data de Expedição' },
      { key: 'dataNascimento', label: 'Data de Nascimento' },
      { key: 'nomeMae', label: 'Nome da Mãe' },
      { key: 'nomePai', label: 'Nome do Pai' },
      { key: 'cpf', label: 'CPF' },
      { key: 'naturalidade', label: 'Naturalidade' },
      { key: 'estadoNasceu', label: 'Estado que Nasceu' },
      { key: 'endereco', label: 'Endereço' },
      { key: 'numero', label: 'Número' },
      { key: 'complemento', label: 'Complemento' },
      { key: 'bairro', label: 'Bairro' },
      { key: 'cidade', label: 'Cidade' },
      { key: 'uf', label: 'UF' },
      { key: 'cep', label: 'Cep' },
      { key: 'login', label: 'Login' },
      { key: 'senha', label: 'Senha' },
      { key: 'nivelPermissao', label: 'Nível de Permissão' },
      { key: 'cargo', label: 'Cargo' },
      { key: 'cltOuCnpj', label: 'CLT ou CNPJ' },
      { key: 'dataAdmissao', label: 'Data de admissão' },
      { key: 'asoValidade', label: 'ASO Validade' },
      { key: 'nr10Validade', label: 'NR10 Validade' },
      { key: 'nr35Validade', label: 'NR35 Validade' },
      { key: 'situacao', label: 'Situação' },
      { key: 'observacao1', label: 'Observação 1' },
      { key: 'observacao2', label: 'Observação 2' },
      { key: 'observacao3', label: 'Observação 3' }
    ]
  },
  siteClaro: {
    key: 'siteClaro',
    title: 'Site Claro',
    baseUrl: '/api/sites-claro',
    route: 'site-claro',
    fields: [
      { key: 'siteId', label: 'ID' },
      { key: 'nome', label: 'Nome' },
      { key: 'anatelTx', label: 'Anatel TX' },
      { key: 'anatelRf', label: 'Anatel RF' },
      { key: 'redeAnatel', label: 'Rede Anatel' },
      { key: 'elevacao', label: 'Elevação' },
      { key: 'latitude', label: 'Latitude' },
      { key: 'longitude', label: 'Longitude' },
      { key: 'latitudeDms', label: 'Latitude DMS' },
      { key: 'longitudeDms', label: 'Longitude DMS' },
      { key: 'clusterGeo', label: 'Cluster GEO' },
      { key: 'datum', label: 'Datum' },
      { key: 'ibge', label: 'IBGE' },
      { key: 'slaInfra', label: 'SLA Infra' },
      { key: 'classificacaoOmr', label: 'Classificação OMR' },
      { key: 'classContrato', label: 'Class Contrato' },
      { key: 'licencasGsmUmtsLte', label: 'Licenças GSM / UMTS / LTE' },
      { key: 'observacao1', label: 'Observação 1' },
      { key: 'observacao2', label: 'Observação 2' },
      { key: 'observacao3', label: 'Observação 3' }
    ]
  },
  siteTim: {
    key: 'siteTim',
    title: 'Site TIM',
    baseUrl: '/api/sites-tim',
    route: 'site-tim',
    fields: [
      { key: 'siteId', label: 'Site ID' },
      { key: 'tipoElemento', label: 'Tipo de Elemento' },
      { key: 'tecnologia', label: 'Tecnologia' },
      { key: 'tipoConexao', label: 'Tipo de Conexão' },
      { key: 'classificacao', label: 'Classificação' },
      { key: 'dataAquisicao', label: 'Data de Aquisição' },
      { key: 'dataConstrucao', label: 'Data de Construção' },
      { key: 'dataAtivacao', label: 'Data de Ativação' },
      { key: 'dataDesativacao', label: 'Data de Desativação' },
      { key: 'justificativa', label: 'Justificativa' },
      { key: 'tipoTorre', label: 'Tipo da Torre' },
      { key: 'aevNominal', label: 'AEV Nominal' },
      { key: 'alturaEstrutura', label: 'Altura da Estrutura' },
      { key: 'statusAtualizacaoSpazio', label: 'Status de Atualização Spazio' }
    ]
  },
  siteVivo: {
    key: 'siteVivo',
    title: 'Site Vivo',
    baseUrl: '/api/sites-vivo',
    route: 'site-vivo',
    fields: [
      { key: 'sequencial', label: 'Sequencial' },
      { key: 'siglaUf', label: 'Sigla UF' },
      { key: 'uf', label: 'UF' },
      { key: 'nome', label: 'Nome' },
      { key: 'sigla', label: 'Sigla' },
      { key: 'siglaGvOiFixa', label: 'Sigla GV / OI / Fixa' },
      { key: 'enderecoSsi', label: 'Endereço SSI' },
      { key: 'altitude', label: 'Altitude' },
      { key: 'pendenciaManutencao', label: 'Pendência Manutenção' },
      { key: 'areaTerceiros', label: 'Área para Terceiros' },
      { key: 'estrutura', label: 'Estrutura' },
      { key: 'siteVip', label: 'Site VIP' },
      { key: 'observacao1', label: 'Observação 1' },
      { key: 'observacao2', label: 'Observação 2' },
      { key: 'observacao3', label: 'Observação 3' }
    ]
  },
  cadastroContratos: {
    key: 'cadastroContratos',
    title: 'Cadastro de Contratos',
    baseUrl: '/api/cadastro-contratos',
    route: 'cadastro-contratos',
    fields: [
      { key: 'clienteDireto', label: 'Cliente Direto' },
      { key: 'gestorClienteDireto', label: 'Gestor Cliente Direto' },
      { key: 'clienteFinal', label: 'Cliente Final' },
      { key: 'gestorClienteFinal', label: 'Gestor Cliente Final' },
      { key: 'projetoTipo', label: 'Projeto Tipo' },
      { key: 'projetoNumero', label: 'Projeto Número' },
      { key: 'oc', label: 'OC' },
      { key: 'os', label: 'OS' },
      { key: 'po', label: 'PO' },
      { key: 'siteId', label: 'Site ID' },
      { key: 'enderecoId', label: 'Endereço ID' },
      { key: 'valorTotalProjeto', label: 'Valor Total do Projeto' },
      { key: 'fasesProjeto', label: 'Fases do Projeto' }
    ]
  },
  chamados: {
    key: 'chamados',
    title: 'Chamados',
    baseUrl: '/api/chamados',
    route: 'chamados',
    fields: [
      { key: 'numeroChamado', label: 'Número do chamado' },
      { key: 'clienteDireto', label: 'Cliente Direto' },
      { key: 'gestorClienteDireto', label: 'Gestor Cliente Direto' },
      { key: 'clienteFinal', label: 'Cliente Final' },
      { key: 'gestorClienteFinal', label: 'Gestor Cliente Final' },
      { key: 'projetoTipo', label: 'Projeto Tipo' },
      { key: 'projetoNumero', label: 'Projeto Número' },
      { key: 'oc', label: 'OC' },
      { key: 'os', label: 'OS' },
      { key: 'po', label: 'PO' },
      { key: 'endereco', label: 'Endereço' },
      { key: 'numero', label: 'Número' },
      { key: 'complemento', label: 'Complemento' },
      { key: 'bairro', label: 'Bairro' },
      { key: 'cidade', label: 'Cidade' },
      { key: 'uf', label: 'UF' },
      { key: 'cep', label: 'Cep' },
      { key: 'latitudeLongitude', label: 'Latitude e Longitude' },
      { key: 'siteTipo', label: 'Site Tipo' },
      { key: 'liberacaoAcessoNumero', label: 'Liberação de Acesso Número' },
      { key: 'tbsaId', label: 'TBSA ID' },
      { key: 'tbsaChamado', label: 'TBSA Chamado' },
      { key: 'descricaoAtividade', label: 'Descrição da Atividade' }
    ]
  }
};

export const getTelecomScreen = (key: string): TelecomScreenConfig | undefined =>
  TELECOM_SCREENS[key];
